export const ValuePropText1 = "En platform til sponsorsøgning, salg og administrationen af sponsorater, som giver jeres forening en totalløsning der gør sponsorarbejdet lettere ved at samle alt et sted.";
export const UdvikletTil = "Udviklet specielt til de danske";
export const ValuePropText2 = "Udskift gamle og ineffektive rutiner og værktøjer med digitale og automatiseret processer, som forenkler og effektivisere arbejdet og giver jeres forening mere tilfredse medlemmer, frivillige og sponsorer og dermed en øget indtægt som i kan bruge i foreningen.";
export const ValueProp3 = "Automatisk oprettet flotte og sælgende sponsortilbud og send dem til jeres sponsorer. Administrer nemt og enkelt alle foreningens sponsorater";
export const ValueProp4 = "Danmarks eneste online sponsoruddannelse specielt lavet til sponsoransvarlige i breddeforeninger.";
export const ValueProp5 = "Individuelle sponsor og event oplæg som udsendes direkte til den enkelte samarbejdspartner og sponsor";
export const ValueProp6 = "Sparring og rådgivning til de sponsoransvarlige i foreningen, i form af blogindlæg, tips og tricks, videoguides, sponsorstrategier og et stærkt community";
export const MissionText = "Vi gør det spændende og let for foreningerne at søge og finde nye samarbejdspartnere og sponsorer, samt ikke mindst ar arbejde struktureret og værdiskabende med disse. Og vi ønsker at tilføre foreningerne den nødvendige viden og læring om udvikling af værdiskabende sponsor og samarbejdsaftaler, så det bliver sjovere og lettere at arbejde med sponsorater.";
export const CTAText = "-få samtidig 3 forslag til nye sponsorer som passer ind i jeres forening!";
export const ProfileTextPeter = "Med flere års erfaring fra DBU som klubudvikler og klubkonsulent, har Peter fingeren på pulsen og er en rigtig foreningsmand"
export const ProfileTextJacob = "Med flere års erfaring fra DBU som klubudvikler og klubkonsulent, har Peter fingeren på pulsen og er en rigtig foreningsmand"
export const ProfileTextKristoffer ="Med flere års erfaring fra DBU som klubudvikler og klubkonsulent, har Peter fingeren på pulsen og er en rigtig foreningsmand"